[project]
name = "font-gen"
version = "0.1.0"
description = "Generates coloured font text for noiting_simulator"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.5",
    "pillow>=12.0.0",
]
